trigger:
- master
  paths:
    include:
    - /AzurePipelines/
    - /MyPkgLib/
    - /MyPkgLib.Tests/

resources:
- repo: self

variables:
  buildConfiguration: Release
  buildPlatform: 'Any CPU'
  vmImage: windows-latest
  ProjectName: MyPkgLib
  SolutionName: azdo-pipelines-yaml-nuget
  major: 1
  minor: 0
  patch: $[counter('myversioncounter', 0)]
  PackageVersion: $(major).$(minor).$(patch)

stages:

- stage: Build
  jobs:
  - template: azure-pipeline.build.yml

- stage: Test
  jobs:
  - template: azure-pipeline.test.yml

- stage: Publish
  jobs:
  - template: azure-pipeline.publish.yml