jobs:
- job: PublishJob
  pool:
    vmImage: $(vmImage)
  steps:
  
  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    inputs:
      command: pack
      configuration: '$(buildConfiguration)'
      packagesToPack: '**/$(ProjectName).csproj' # Required when command == pack
      #packDirectory: '$(Build.ArtifactStagingDirectory)'   #this should be the Pipeline download directory but didn't figure that out yet
      versioningScheme: byEnvVar      # Options: off, byPrereleaseNumber, byEnvVar, byBuildNumber
      versionEnvVar: PackageVersion   # Required when versioningScheme == byEnvVar
      verbosityPack: normal
      buildProperties: 'SymbolPackageFormat=snupkg'

  - task: NuGetCommand@2
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: f2calvNuGetInt
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'