trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - /AzurePipelines/
    - /MyPkgLib/
    - /MyPkgLib.Tests/
    exclude:
    - README.md

resources:
- repo: self

variables:
  buildConfiguration: Release
  buildPlatform: 'Any CPU'
  vmImage: windows-latest
  ProjectName: MyPkgLib
  SolutionName: azdo-pipelines-yaml-nuget
  publishFeedCredentials: f2calvNuGet
  Version.Major: 1
  Version.Minor: 2
  Version.PackageMajorMinor: '$(Version.Minor).$(Version.Major)-$(ProjectName)'
  Version.Revision: $[counter(variables['Version.PackageMajorMinor'], 0)]
  PackageVersion: $(Version.Major).$(Version.Minor).$(Version.Revision)

stages:

- stage: Build
  jobs:
  - template: azure-pipeline.build.yml

- stage: Test
  jobs:
  - template: azure-pipeline.test.yml

#- stage: Publish
#  jobs:
#  - template: azure-pipeline.publish.yml