jobs:
- job: BuildJob
  pool:
    vmImage: $(vmImage)
  steps:
  
  - task: DotNetCoreCLI@2
    displayName: dotnet restore script
    inputs:
      command: 'restore'
      projects: '$(SolutionName).sln'
  
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      projects: '$(SolutionName).sln'
      arguments: '--configuration $(buildConfiguration)'