jobs:
- job: BuildJob
  pool:
    vmImage: $(vmImage)
  steps:
  
  - task: DotNetCoreCLI@2
    displayName: dotnet restore script
    inputs:
      command: 'restore'
      #projects: '$(SolutionName).sln'
      projects: |
        **/$(ProjectName).csproj
        **/$(ProjectName).Tests.csproj
  
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      #projects: '$(SolutionName).sln'
      projects: |
        **/$(ProjectName).csproj
        **/$(ProjectName).Tests.csproj
      arguments: '--configuration $(buildConfiguration)'